### ISSUE TITLE
Map and Icons seem a little... off...

### ISSUE THREAD

**Issue by killeand** [matzman666/PyPipboyApp#49]
Is anyone else having this issue with the map and icons not matching up?

![mapproblem](https://cloud.githubusercontent.com/assets/16377274/12739014/41a93612-c92b-11e5-8625-df95bfae8141.png)

For reference, the top left corner of the graphics view is the Sanctuary island. 

I played around with setting the map zoom, and icon scale sizes, and then restarted the app. No such luck, it appears to stay the same. I have tried using this on the original map, the satellite, and satellite color maps. 

I THINK this happened after I updated my repository near the 0.8 release.

**Comment by matzman666** [comment]
Ok, that shouldn't happen. I tweaked the map calibration points a bit (the corresponding commit is 41f7d63595b6491ad1833f488ca560fc9d243695) to improve the accuracy of map marker placement. And on my system it works perfectly. It's really strange that on your systems the markers are off by a very large amount. Could you play a bit with the map calibration points and see what happens if you change them?

**Comment by killeand** [comment]
Those are some super funky numbers to play with. I didn't quite get the exact fit, but close enough for a general test:

![maptest1](https://cloud.githubusercontent.com/assets/16377274/12770994/01b78246-c9eb-11e5-92ef-afd6d673303c.png)

Here is the JSON data:

```
        "label": "Satellite View",
        "colorable": true,
        "file": "satview.jpg",
        "nw": [-1800, -1350],
        "ne": [5800, -1350],
        "sw": [-1800, 5800]
```

**Comment by matzman666** [comment]
I suppose you have the [Satellite World Map](http://www.nexusmods.com/fallout4/mods/8989) mod installed. I get the exact same marker placement pattern as you when I use it. This mod changes the cell coordinates of the commonwealth worldspace record. The cell coordinates are apparently used to calculate the /Map/World/Extends coordinates, which I am using to know where to place the map markers.

The easiest solution would be to just hardcode those coordinates. There is actually no reason to use the values provided by the game, I just didn't know better when I coded the relevant parts.

**Comment by killeand** [comment]
Ah yes, mods strike a blow. Yes, I do have that installed, and its highlight corresponds with the timing. 

I wonder what is going to happen when they decide to introduce a second worldspace in a DLC.

This probably isn't a priority for a fix, but shall I keep this open as a reminder?

**Comment by matzman666** [comment]
It's already fixed in the newest version, therefore I close it.

The game tells us which map we are supposed to display c(urrently we are ignoring this). With a new worldspace the game will probably tell us to display a different map, and from the map name we should be able to tell which worldspace is currently active.

**Comment by luckydonald** [comment]
What is the official app doing with them coordinates?

**Comment by matzman666** [comment]
Fallout 4 also sends a map file path together with the coordinates. The coordinates are most probably used to "calibrate" the map file so that the map marker are placed correctly.

**Comment by luckydonald** [comment]
I am curious,
the filename/path only, or actual data?
I found `$.map.world.worldmaptexture`
![image](https://cloud.githubusercontent.com/assets/2737108/13029644/2d5412ac-d292-11e5-9271-506cb92a40e0.png)

**Comment by matzman666** [comment]
Yes, that is what I meant.
